/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Sun May 11 22:07:52 CEST 2014
* Mission file name: TFAR-Test.Altis
* Mission name: TFAR-Test.Altis
* Required mods:
* + ArmA 3
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//Empty, nothing to do. unit box_scopes
//Empty, nothing to do. unit box_weapon
//Empty, nothing to do. unit box_ammo

/**
* Loadout for soldiers units
*/

if (player == Ausbilder) exitwith {
removeallweapons Ausbilder;
removeallassigneditems Ausbilder;
removeHeadgear Ausbilder;
removeBackpack Ausbilder;
removeVest Ausbilder;

Ausbilder addWeapon "ItemMap";
Ausbilder addWeapon "ItemWatch";
Ausbilder addWeapon "ItemCompass";
Ausbilder addWeapon "ItemGPS";
Ausbilder addWeapon "H_MilCap_dgtl";
Ausbilder addWeapon "Binocular";
Ausbilder addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Ausbilder);
clearMagazineCargoGlobal (vestContainer Ausbilder);
clearWeaponCargoGlobal (vestContainer Ausbilder);
clearItemCargoGlobal (uniformContainer Ausbilder);
clearMagazineCargoGlobal (uniformContainer Ausbilder);
clearWeaponCargoGlobal (uniformContainer Ausbilder);
if (count weapons Ausbilder > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Ausbilder) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Ausbilder selectWeapon (_muzzles select 0);
  }
  else {
     Ausbilder selectWeapon _type;
  };
};
};

if (player == Soldat_1) exitwith {
removeallweapons Soldat_1;
removeallassigneditems Soldat_1;
removeHeadgear Soldat_1;
removeBackpack Soldat_1;
removeVest Soldat_1;

Soldat_1 addWeapon "ItemMap";
Soldat_1 addWeapon "ItemWatch";
Soldat_1 addWeapon "ItemCompass";
Soldat_1 addWeapon "ItemGPS";
Soldat_1 addWeapon "H_Booniehat_grn";
Soldat_1 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_1);
clearMagazineCargoGlobal (vestContainer Soldat_1);
clearWeaponCargoGlobal (vestContainer Soldat_1);
clearItemCargoGlobal (uniformContainer Soldat_1);
clearMagazineCargoGlobal (uniformContainer Soldat_1);
clearWeaponCargoGlobal (uniformContainer Soldat_1);
if (count weapons Soldat_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_1 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_1 selectWeapon _type;
  };
};
};

if (player == Soldat_2) exitwith {
removeallweapons Soldat_2;
removeallassigneditems Soldat_2;
removeHeadgear Soldat_2;
removeBackpack Soldat_2;
removeVest Soldat_2;

Soldat_2 addWeapon "ItemMap";
Soldat_2 addWeapon "ItemWatch";
Soldat_2 addWeapon "ItemCompass";
Soldat_2 addWeapon "ItemGPS";
Soldat_2 addWeapon "H_Booniehat_grn";
Soldat_2 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_2);
clearMagazineCargoGlobal (vestContainer Soldat_2);
clearWeaponCargoGlobal (vestContainer Soldat_2);
clearItemCargoGlobal (uniformContainer Soldat_2);
clearMagazineCargoGlobal (uniformContainer Soldat_2);
clearWeaponCargoGlobal (uniformContainer Soldat_2);
if (count weapons Soldat_2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_2 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_2 selectWeapon _type;
  };
};
};

if (player == Soldat_3) exitwith {
removeallweapons Soldat_3;
removeallassigneditems Soldat_3;
removeHeadgear Soldat_3;
removeBackpack Soldat_3;
removeVest Soldat_3;

Soldat_3 addWeapon "ItemMap";
Soldat_3 addWeapon "ItemWatch";
Soldat_3 addWeapon "ItemCompass";
Soldat_3 addWeapon "ItemGPS";
Soldat_3 addWeapon "H_Booniehat_grn";
Soldat_3 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_3);
clearMagazineCargoGlobal (vestContainer Soldat_3);
clearWeaponCargoGlobal (vestContainer Soldat_3);
clearItemCargoGlobal (uniformContainer Soldat_3);
clearMagazineCargoGlobal (uniformContainer Soldat_3);
clearWeaponCargoGlobal (uniformContainer Soldat_3);
if (count weapons Soldat_3 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_3) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_3 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_3 selectWeapon _type;
  };
};
};

if (player == Soldat_4) exitwith {
removeallweapons Soldat_4;
removeallassigneditems Soldat_4;
removeHeadgear Soldat_4;
removeBackpack Soldat_4;
removeVest Soldat_4;

Soldat_4 addWeapon "ItemMap";
Soldat_4 addWeapon "ItemWatch";
Soldat_4 addWeapon "ItemCompass";
Soldat_4 addWeapon "ItemGPS";
Soldat_4 addWeapon "H_Booniehat_grn";
Soldat_4 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_4);
clearMagazineCargoGlobal (vestContainer Soldat_4);
clearWeaponCargoGlobal (vestContainer Soldat_4);
clearItemCargoGlobal (uniformContainer Soldat_4);
clearMagazineCargoGlobal (uniformContainer Soldat_4);
clearWeaponCargoGlobal (uniformContainer Soldat_4);
if (count weapons Soldat_4 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_4) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_4 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_4 selectWeapon _type;
  };
};
};

if (player == Soldat_5) exitwith {
removeallweapons Soldat_5;
removeallassigneditems Soldat_5;
removeHeadgear Soldat_5;
removeBackpack Soldat_5;
removeVest Soldat_5;

Soldat_5 addWeapon "ItemMap";
Soldat_5 addWeapon "ItemWatch";
Soldat_5 addWeapon "ItemCompass";
Soldat_5 addWeapon "ItemGPS";
Soldat_5 addWeapon "H_Booniehat_grn";
Soldat_5 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_5);
clearMagazineCargoGlobal (vestContainer Soldat_5);
clearWeaponCargoGlobal (vestContainer Soldat_5);
clearItemCargoGlobal (uniformContainer Soldat_5);
clearMagazineCargoGlobal (uniformContainer Soldat_5);
clearWeaponCargoGlobal (uniformContainer Soldat_5);
if (count weapons Soldat_5 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_5) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_5 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_5 selectWeapon _type;
  };
};
};

if (player == Soldat_6) exitwith {
removeallweapons Soldat_6;
removeallassigneditems Soldat_6;
removeHeadgear Soldat_6;
removeBackpack Soldat_6;
removeVest Soldat_6;

Soldat_6 addWeapon "ItemMap";
Soldat_6 addWeapon "ItemWatch";
Soldat_6 addWeapon "ItemCompass";
Soldat_6 addWeapon "ItemGPS";
Soldat_6 addWeapon "H_Booniehat_grn";
Soldat_6 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_6);
clearMagazineCargoGlobal (vestContainer Soldat_6);
clearWeaponCargoGlobal (vestContainer Soldat_6);
clearItemCargoGlobal (uniformContainer Soldat_6);
clearMagazineCargoGlobal (uniformContainer Soldat_6);
clearWeaponCargoGlobal (uniformContainer Soldat_6);
if (count weapons Soldat_6 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_6) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_6 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_6 selectWeapon _type;
  };
};
};

if (player == Soldat_7) exitwith {
removeallweapons Soldat_7;
removeallassigneditems Soldat_7;
removeHeadgear Soldat_7;
removeBackpack Soldat_7;
removeVest Soldat_7;

Soldat_7 addWeapon "ItemMap";
Soldat_7 addWeapon "ItemWatch";
Soldat_7 addWeapon "ItemCompass";
Soldat_7 addWeapon "ItemGPS";
Soldat_7 addWeapon "H_Booniehat_grn";
Soldat_7 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_7);
clearMagazineCargoGlobal (vestContainer Soldat_7);
clearWeaponCargoGlobal (vestContainer Soldat_7);
clearItemCargoGlobal (uniformContainer Soldat_7);
clearMagazineCargoGlobal (uniformContainer Soldat_7);
clearWeaponCargoGlobal (uniformContainer Soldat_7);
if (count weapons Soldat_7 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_7) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_7 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_7 selectWeapon _type;
  };
};
};

if (player == Soldat_8) exitwith {
removeallweapons Soldat_8;
removeallassigneditems Soldat_8;
removeHeadgear Soldat_8;
removeBackpack Soldat_8;
removeVest Soldat_8;

Soldat_8 addWeapon "ItemMap";
Soldat_8 addWeapon "ItemWatch";
Soldat_8 addWeapon "ItemCompass";
Soldat_8 addWeapon "ItemGPS";
Soldat_8 addWeapon "H_Booniehat_grn";
Soldat_8 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_8);
clearMagazineCargoGlobal (vestContainer Soldat_8);
clearWeaponCargoGlobal (vestContainer Soldat_8);
clearItemCargoGlobal (uniformContainer Soldat_8);
clearMagazineCargoGlobal (uniformContainer Soldat_8);
clearWeaponCargoGlobal (uniformContainer Soldat_8);
if (count weapons Soldat_8 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_8) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_8 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_8 selectWeapon _type;
  };
};
};

if (player == Soldat_9) exitwith {
removeallweapons Soldat_9;
removeallassigneditems Soldat_9;
removeHeadgear Soldat_9;
removeBackpack Soldat_9;
removeVest Soldat_9;

Soldat_9 addWeapon "ItemMap";
Soldat_9 addWeapon "ItemWatch";
Soldat_9 addWeapon "ItemCompass";
Soldat_9 addWeapon "ItemGPS";
Soldat_9 addWeapon "H_Booniehat_grn";
Soldat_9 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Soldat_9);
clearMagazineCargoGlobal (vestContainer Soldat_9);
clearWeaponCargoGlobal (vestContainer Soldat_9);
clearItemCargoGlobal (uniformContainer Soldat_9);
clearMagazineCargoGlobal (uniformContainer Soldat_9);
clearWeaponCargoGlobal (uniformContainer Soldat_9);
if (count weapons Soldat_9 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Soldat_9) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Soldat_9 selectWeapon (_muzzles select 0);
  }
  else {
     Soldat_9 selectWeapon _type;
  };
};
};

if (player == Player1) exitwith {
removeallweapons Player1;
removeallassigneditems Player1;
removeHeadgear Player1;
removeBackpack Player1;
removeVest Player1;

Player1 addWeapon "ItemMap";
Player1 addWeapon "ItemWatch";
Player1 addWeapon "ItemCompass";
Player1 addWeapon "ItemGPS";
Player1 addWeapon "H_MilCap_dgtl";
Player1 addWeapon "Binocular";
Player1 addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Player1);
clearMagazineCargoGlobal (vestContainer Player1);
clearWeaponCargoGlobal (vestContainer Player1);
clearItemCargoGlobal (uniformContainer Player1);
clearMagazineCargoGlobal (uniformContainer Player1);
clearWeaponCargoGlobal (uniformContainer Player1);
if (count weapons Player1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Player1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Player1 selectWeapon (_muzzles select 0);
  }
  else {
     Player1 selectWeapon _type;
  };
};
};

