/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Sun May 11 21:53:46 CEST 2014
* 
* Call the script: _dummy = this execvm "TFAR_ammo.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

  _this addmagazinecargoGlobal ["10Rnd_762x51_Mag",50];
  _this addmagazinecargoGlobal ["11Rnd_45ACP_Mag",20];
  _this addmagazinecargoGlobal ["30Rnd_9x21_Mag",50];
  _this addmagazinecargoGlobal ["9Rnd_45ACP_Mag",20];
  _this addmagazinecargoGlobal ["16Rnd_9x21_Mag",20];
  _this addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Green",50];
  _this addmagazinecargoGlobal ["30Rnd_65x39_caseless_green_mag_Tracer",50];
  _this addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",20];
};
