/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Sun May 11 20:37:55 CEST 2014
* 
* Call the script: _dummy = this execvm "TFAR_scopes.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

  _this additemcargoGlobal ["optic_Hamr",20];
  _this additemcargoGlobal ["optic_Arco",20];
  _this additemcargoGlobal ["optic_Aco",20];
  _this additemcargoGlobal ["optic_MRCO",20];
  _this additemcargoGlobal ["optic_Holosight",20];
};
