/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Sun May 11 20:38:11 CEST 2014
* 
* Call the script: _dummy = this execvm "TFAR_weapon.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

  _this addweaponcargoGlobal ["srifle_DMR_01_F",20];
  _this addweaponcargoGlobal ["arifle_TRG20_F",20];
  _this addweaponcargoGlobal ["arifle_SDAR_F",20];
  _this addweaponcargoGlobal ["hgun_ACPC2_F",20];
  _this addweaponcargoGlobal ["arifle_Katiba_F",20];
  _this addweaponcargoGlobal ["arifle_TRG21_F",20];
  _this addweaponcargoGlobal ["hgun_Pistol_heavy_01_F",20];
  _this addweaponcargoGlobal ["SMG_02_F",20];
  _this addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",20];
  _this addweaponcargoGlobal ["hgun_PDW2000_F",20];
};
